version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    links:
      - fpm

    # We limit Linux capabilities...
    # see https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
    cap_drop:
      - ALL
    cap_add:
      - CHOWN  # Make arbitrary changes to file UIDs and GIDs (see chown(2)).
      - NET_BIND_SERVICE  # Bind a socket to internet domain privileged ports (port numbers less than 1024).
      - SETUID  # Make arbitrary manipulations of process UIDs.
      - SETGID  # Make arbitrary manipulations of process GIDs and supplementary GID list.


  fpm:
    build:
      context: .
      dockerfile: Dockerfile.phpfpm
      args:
        # Switches ./configs/php.ini-* file
        # set `production` or `development`
        - BUILD_TYPE=production
    ports:
      - 9000
    # seems like fpm receives the full path from nginx
    # and tries to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
      - ./src:/task

    # We limit Linux capabilities...
    # see https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
    cap_drop:
      - ALL
    cap_add:
      - SETUID  # Make arbitrary manipulations of process UIDs.
      - SETGID  # Make arbitrary manipulations of process GIDs and supplementary GID list.

